#include  <iostream>
using namespace std;


int main () {

	int club;
	cout<<"PILIH NAMA CLUB : ";
	cin>> club ;
	switch ( club ) {
		
		case 1 :
			cout<<"Bali United"<<endl;
			cout<<"--NAMA NAMA PEMAINNYA--"<<endl;		
			cout<<"Nadeo Argawinata"<<endl;
			cout<<"Rakasurya Handika"<<endl;
			cout<<"Irfan Jaya"<<endl;
			cout<<"Haudi Abdillah"<<endl;
			cout<<"Brwa Nouri"<<endl;
			cout<<"Sidik Saimima"<<endl;
			cout<<"Ardi Idrus"<<endl;
			cout<<"Ilija Spasojevic"<<endl;
			cout<<"Eber Bessa"<<endl;
			cout<<"Yabes Roni"<<endl;
			cout<<"Gunawan Dwi Cahyo"<<endl;
			cout<<"Fadhil Sausu"<<endl;
			cout<<"Hendra Bayauw"<<endl;
			cout<<"Hariono"<<endl;
			cout<<"Ahmad Agung"<<endl;
			cout<<"Rizky Pellu"<<endl;
			cout<<"Lerby Eliandry"<<endl;
			cout<<"Novri Setiawan"<<endl;
			cout<<"Ricky Fajrin"<<endl;
			cout<<"Komang Tri Arta"<<endl;
			cout<<"Leonard Tupamahu"<<endl;
			cout<<"I Made Andhika Wijaya"<<endl;
			cout<<"Privat Mbarga"<<endl;
			cout<<"Willian Pacheco"<<endl;
			cout<<"I Made Tito Wiratama"<<endl;
			cout<<"I Gede Agus Mahendra"<<endl;
			cout<<"I Komang Aryantara"<<endl;
			cout<<"Jajang Mulyana"<<endl;
			cout<<"Kadek Dimas Satria"<<endl;
			cout<<"Ramdani Lestaluhu"<<endl;
			cout<<"Muhammad Ridho"<<endl;
			cout<<"Rahmat"<<endl;
			break;
		
		case 2 :
			cout<<"barito Putera"<<endl;
			cout<<"--NAMA NAMA PEMAINNYA--"<<endl;
			cout<<"Joko Ribowo"<<endl;
			cout<<"Aditya Harlan"<<endl;
			cout<<"Norhalid"<<endl;
			cout<<"Yogi Hermawan"<<endl;
			cout<<"Renan Alves"<<endl;
			cout<<"Luthfi Kamal"<<endl;
			cout<<"Donny Munim"<<endl;
			cout<<"M.Firly"<<endl;
			cout<<"Yuswanto Aditya"<<endl;
			cout<<"M.Helmi"<<endl;
			cout<<"Frank Sokoy"<<endl;
			cout<<"Rendy Saputra"<<endl;
			cout<<"Alexandro Kamuru"<<endl;
			cout<<"Baggas Kaffa"<<endl;
			cout<<"Nazar Nurzaidin"<<endl;
			cout<<"Dendi Maulana"<<endl;
			cout<<"Bayu Pradana"<<endl;
			cout<<"Rafli Syahril"<<endl;
			cout<<"Ferdiansyah"<<endl;
			cout<<"Aditya Daffa"<<endl;
			cout<<"Ryota Noma"<<endl;
			cout<<"Alif Jaelani"<<endl;
			cout<<"Buyung Ismu Lessy"<<endl;
			cout<<"Slamet Budiono"<<endl;
			cout<<"Rafinha"<<endl;
			cout<<"Rizky Pora"<<endl;
			cout<<"Amrizal Umanailo"<<endl;
			cout<<"Rafael Silva"<<endl;
			cout<<"Afdal Yusra"<<endl;
			cout<<"Riski Kurniawan"<<endl;
			cout<<"Rahmat Beri Santoso"<<endl;
			break;
			
		case 3 :
			cout<<"Bhayangkara FC"<<endl;
			cout<<"--NAMA NAMA PEMAINNYA--"<<endl;
			cout<<"Aqil Savik"<<endl;
			cout<<"Putu Gede"<<endl;
			cout<<"Dodi Irawan"<<endl;
			cout<<"Annderson Salles"<<endl;
			cout<<"M.Faturrohman"<<endl;
			cout<<"Aji Joko Sutopo"<<endl;
			cout<<"Abdul Rachman"<<endl;
			cout<<"Muhammad Hargianto"<<endl;
			cout<<"Adam Najem"<<endl;
			cout<<"Younes Mokhtar"<<endl;
			cout<<"Awan Seto"<<endl;
			cout<<"Ichwan Tuharea"<<endl;
			cout<<"Ruben Sanadi"<<endl;
			cout<<"Finky Pasamba"<<endl;
			cout<<"Antoni Nugroho"<<endl;
			cout<<"Teuku Ichsan"<<endl;
			cout<<"Sani Rizki"<<endl;
			cout<<"Titan Agung"<<endl;
			cout<<"Dendy Sulistyawan"<<endl;
			cout<<"Wahyu Suboseto"<<endl;
			cout<<"Indra Kahfi"<<endl;
			cout<<"Alsan Sanda"<<endl;
			cout<<"Reza Kusuma "<<endl;
			cout<<"Andik Vermansah"<<endl;
			cout<<"Dimas Pamungkas"<<endl;
			cout<<"Nurhidayat"<<endl;
			cout<<"Indra Adi Nugraha"<<endl;
			cout<<"Frezy AL Hudaifi"<<endl;
			cout<<"Surya Maulana"<<endl;
			cout<<"Faiz Maulana"<<endl;
			cout<<"Aprius Surbay"<<endl;
			cout<<"Asyraq Gufron"<<endl;
			cout<<"Kasim Botan"<<endl;
			cout<<"David Maulana"<<endl;
			cout<<"Panggih Prio"<<endl;
			cout<<"Youssef Ezzejjari"<<endl;
			break;
			
		case 4 :
			cout<<"Cilegon United"<<endl;
			cout<<"--NAMA NAMA PEMAINNYA--"<<endl;
			cout<<"Edo Febriansyah"<<endl;
			cout<<"O.K.John"<<endl;
			cout<<"Saddam Hi Tenang"<<endl;
			cout<<"Makan Konate"<<endl;
			cout<<"Syamsir Alam"<<endl;
			cout<<"Ihsan Zikrak"<<endl;
			cout<<"Wander Luiz"<<endl;
			cout<<"Christian Gonzales"<<endl;
			cout<<"Gamalia Imbiri"<<endl;
			cout<<"Jujun junaedi"<<endl;
			cout<<"Kurniawan Karman"<<endl;
			cout<<"Victor Sallinas"<<endl;
			cout<<"Fadli Akbar"<<endl;
			cout<<"Sumarna"<<endl;
			cout<<"Herwin Tri Saputra"<<endl;
			cout<<"Arthur Bonai"<<endl;
			cout<<"Andy Setiawan"<<endl;
			cout<<"Hamdan Zamzani"<<endl;
			cout<<"Fiqri"<<endl;
			cout<<"Wawan Hendrawan"<<endl;
			cout<<"Meru Kimura"<<endl;
			cout<<"Arif satria"<<endl;
			cout<<"Sandi sute"<<endl;
			cout<<"Bima Ragil"<<endl;
			cout<<"Mitsuru Maruoka"<<endl;
			cout<<"Defri Rizki"<<endl;
			cout<<"David Laly"<<endl;
			cout<<"Alfin Tuasalamony"<<endl;
			cout<<"Romadona Dwi Kusuma"<<endl;
			cout<<"Hilmansyah"<<endl;
			cout<<"Wahyudi"<<endl;
			cout<<"Septian Bagaskara"<<endl;
			break;
			
		case 5 :
			cout<<"Dewa United"<<endl;
			cout<<"--NAMA NAMA PEMAINYA--"<<endl;
			cout<<"Muhammad Natshir"<<endl;
			cout<<"mochamad Zaenuri"<<endl;
			cout<<"Asep Berliaan"<<endl;
			cout<<"Risto Mitrevski"<<endl;
			cout<<"Theo Numberi"<<endl;
			cout<<"Subhan Fajri"<<endl;
			cout<<"Reksa Maulana"<<endl;
			cout<<"Rishadi Fauzi"<<endl;
			cout<<"Karim Rossi"<<endl;
			cout<<"Abi Defa Marendra"<<endl;
			cout<<"Bhudiar Riza"<<endl;
			cout<<"Miftah Anwar Sani"<<endl;
			cout<<"Rangga Muslim"<<endl;
			cout<<"Jajang Sukmara"<<endl;
			cout<<"Majed Osman"<<endl;
			cout<<"Diya Ramadhan"<<endl;
			cout<<"Dias Angga Putra"<<endl;
			cout<<"Ichsan Kurniawan"<<endl;
			cout<<"Risna Prahabalena"<<endl;
			cout<<"Syaiful"<<endl;
			cout<<"Utam Rusdiana"<<endl;
			cout<<"Achmad Faris"<<endl;
			cout<<"Randy May"<<endl;
			cout<<"Anwar Sani"<<endl;
			cout<<"Nasir"<<endl;
			cout<<"Herry Susilo"<<endl;
			cout<<"Mokhamad Syaifudin"<<endl;
			cout<<"Akbar Zakaria"<<endl;
			cout<<"Lucas Ramos"<<endl;
			cout<<"Desly Nur"<<endl;
			cout<<"Fahmi Al Ayyubi"<<endl;
			break;
			
		case 6 :
			cout<<"Arema FC"<<endl;
			cout<<"--NAMA NAMA PEMAINYA--"<<endl;
			cout<<" Dendi Santoso "<<endl;
			cout<<"Genta Alpredo"<<endl;
			cout<<"Bramantio Ramadhan"<<endl;
			cout<<"Johann Alfarizi"<<endl;
			cout<<"Vikrian Akbar"<<endl;
			cout<<"Adilson Maringga"<<endl;
			cout<<"Kushedya Hari Yudo"<<endl;
			cout<<"Teguh Amirudin"<<endl;
			cout<<"Diego Michels"<<endl;
			cout<<"Achamd Figo"<<endl;
			cout<<"Dedik Setiawan"<<endl;
			cout<<"Seiya Da Costa Lay"<<endl;
			cout<<"Sandi Sute"<<endl;
			cout<<"Andriyas Francissco"<<endl;
			cout<<"Didik Ariyanto"<<endl;
			cout<<"Rizky Dwi Febrianto"<<endl;
			cout<<"Hamzah Titofani"<<endl;
			cout<<"Jayus Hariono"<<endl;
			cout<<"Fabiano Beltrame"<<endl;
			cout<<"Ridwan Tawainela"<<endl;
			cout<<"Faiz Iqbal"<<endl;
			cout<<"Hanif Sjahbandi"<<endl;
			cout<<"Aji Saka"<<endl;
			cout<<"Sergio Silva"<<endl;
			cout<<"Bagas Adi Nugroho"<<endl;
			cout<<"Ikhfanul Alam"<<endl;
			cout<<"Ryan Kurnia"<<endl;
			cout<<"Renshi Yamaguchi"<<endl;
			cout<<"Muhhammad Rafli"<<endl;
			cout<<"Feby Eka Putra"<<endl;
			break;
			
		case 7 :
			cout<<"Madura United"<<endl;
			cout<<"--NAMA NAMA PEMAINYA--"<<endl;
			cout<<"Fakhrurrazi Quba"<<endl;
			cout<<"Fawaid Ansori"<<endl;
			cout<<"Rendy Oscario"<<endl;
			cout<<"Miswar Saputra"<<endl;
			cout<<"Fachrudin A"<<endl;
			cout<<"Kadek Raditya"<<endl;
			cout<<"Reva Adi Utama"<<endl;
			cout<<"Novan Setya"<<endl;
			cout<<"Fadhilah Nur"<<endl;
			cout<<"Birrul Walidain"<<endl;
			cout<<"Alex Vanjin"<<endl;
			cout<<"Guntur Ariyandi"<<endl;
			cout<<"Zulfiandi"<<endl;
			cout<<"Feby Ramzi"<<endl;
			cout<<"Hugo Gomes"<<endl;
			cout<<"Kevy Syahertian"<<endl;
			cout<<"Slamet Nur Cahyo"<<endl;
			cout<<"Maulana R"<<endl;
			cout<<"Rivaldi Bawuo"<<endl;
			cout<<"Haris Tuharea"<<endl;
			cout<<"Esteban Vizcara"<<endl;
			cout<<"Erik Sanjaya"<<endl;
			cout<<"Malik Risaldi"<<endl;
			cout<<"Ronaldo Kwateh"<<endl;
			cout<<"Bayu Gatra"<<endl;
			cout<<"Beto Goncalves"<<endl;
			cout<<"M Aldo Maulidino"<<endl;
			break;
			
		case 8 :
			cout<<"Persita Tanggerang"<<endl;
			cout<<"--NAMA NAMA PEMAINYA--"<<endl;
			cout<<"Dedi Sulaiman"<<endl;
			cout<<"Rizky Darmawan"<<endl;
			cout<<"Darmawan"<<endl;
			cout<<"Dhika Bhayangkara"<<endl;
			cout<<"Agustin Cattaneo"<<endl;
			cout<<"Dominggus Fakdewar"<<endl;
			cout<<"Charisma Fathoni"<<endl;
			cout<<"Elisna Basna"<<endl;
			cout<<"Muhammad Toha"<<endl;
			cout<<"Andika Reynaldo"<<endl;
			cout<<"Irvan Febrianto"<<endl;
			cout<<"Abu Rizal Maulana"<<endl;
			cout<<"Israel Wamiau"<<endl;
			cout<<"Arif Setiawan"<<endl;
			cout<<"Duta Atapelwa"<<endl;
			cout<<"Yohanes Kandaimu"<<endl;
			cout<<"Mhammad Rifqi"<<endl;
			cout<<"Mario Jardel"<<endl;
			cout<<"Mahmud Cahyono"<<endl;
			cout<<"Dadang apridiyanto"<<endl;
			cout<<"Ezequiel Vidal"<<endl;
			cout<<"Imam Zakiri"<<endl;
			cout<<"Flavio Cameron"<<endl;
			cout<<"Paulo Sitanggang"<<endl;
			cout<<"Adittia Gigis"<<endl;
			cout<<"Bae Sin Yeong"<<endl;
			cout<<"Mohammad Afganiladin"<<endl;
			cout<<"Ghozali Siregar"<<endl;
			cout<<"Fahreza Sudin"<<endl;
			cout<<"Nelson Alom"<<endl;
			cout<<"Muhammad Iqbal"<<endl;
			cout<<"Osas Saha"<<endl;
			cout<<"Ramiro Fergonzi"<<endl;
			cout<<"Oktavianus Karisago"<<endl;
			cout<<"Wilda Ramdani"<<endl;
			cout<<"Survi Arpani"<<endl;;
			break;
			
		case 9 :
			cout<<"PSM Makasar"<<endl;
			cout<<"--NAMA NAMA PEMAINNYA--"<<endl;
			cout<<"Muhammad Ardiansyah"<<endl;
			cout<<"Yuran Fernandesh"<<endl;
			cout<<"Erwin Gutawa"<<endl;
			cout<<"Benjamin Dethan"<<endl;
			cout<<"Bryan Caesar"<<endl;
			cout<<"Ramadhan Sananta"<<endl;
			cout<<"Everton"<<endl;
			cout<<"Yance Sayuri"<<endl;
			cout<<"Ricky Pratama"<<endl;
			cout<<"Rasyid Bakri"<<endl;
			cout<<"Rivky Mokodompit"<<endl;
			cout<<"Annas Firanto"<<endl;
			cout<<"Yakob Sayuri"<<endl;
			cout<<"Rizky Eka Pratama"<<endl;
			cout<<"Vivi Azrisal"<<endl;
			cout<<"Ganjar Mukti"<<endl;
			cout<<"Safrudin Tahhar"<<endl;
			cout<<"Abdul Rahman"<<endl;
			cout<<"Reza Arya Pratama"<<endl;
			cout<<"Sanuel Christianson"<<endl;
			cout<<"Dallen Doke"<<endl;
			cout<<"Dzaky Asraf"<<endl;
			cout<<"Kenzo Nambu"<<endl;
			cout<<"Akbar Tanjung"<<endl;
			cout<<"Agung Mannan"<<endl;
			cout<<"Muhammad Arfan"<<endl;
			cout<<"Harlan Suardi"<<endl;
			cout<<"Rafli Asrul"<<endl;
			cout<<"Edgard Amping"<<endl;
			cout<<"Wiljan Pluim"<<endl;
			break;
				
		case 10 :
			cout<<"Persija Jakarta"<<endl;
			cout<<"--NAMA NAMA PEMAINYA--"<<endl;
			cout<<"Andritany"<<endl;
			cout<<"Cahya Supriadi"<<endl;
			cout<<"Risky Sudirman"<<endl;
			cout<<"Andre Arido"<<endl;
			cout<<"Ondrej Kudela"<<endl;
			cout<<"Ryuji Utomo"<<endl;
			cout<<"Hansamu yama"<<endl;
			cout<<"Muhammad Ferrari"<<endl;
			cout<<"Otavio Dutra"<<endl;
			cout<<"Maman abdurahman"<<endl;
			cout<<"Firza Andika"<<endl;
			cout<<"Rizaldi Hehanusa"<<endl;
			cout<<"Frengky Missa"<<endl;
			cout<<"Rangga Widiansyah"<<endl;
			cout<<"Hamra Hehanusa"<<endl;
			cout<<"ISmed Sofyan"<<endl;
			cout<<"Rio Fahmi"<<endl;
			cout<<"Haanif Syahbandi"<<endl;
			cout<<"Resky Fandi"<<endl;
			cout<<"Dwiki Arya"<<endl;
			cout<<"Syahwal Ginting"<<endl;
			cout<<"Braif Fatari"<<endl;
			cout<<"Dony Pamungkas"<<endl;
			cout<<"Raka Cahyana"<<endl;
			cout<<"Osvaldo Hay"<<endl;
			cout<<"Riko Simanjuntak"<<endl;
			cout<<"Alfriyanto Nico"<<endl;
			cout<<"Michael Krmencik"<<endl;
			cout<<"Yusuf"<<endl;
			cout<<"Taufik Hidayat"<<endl;
			break;
			
		case 11 :
			cout<<"Persebaya Surabaya"<<endl;
			cout<<"--NAMA NAMA PEMAINYA--"<<endl;
			cout<<"Ernando Ari"<<endl;
			cout<<"Andhika Rama "<<endl;
			cout<<"Gede Dida"<<endl;
			cout<<"Satria Tama"<<endl;
			cout<<"Mochamad Zaenuri"<<endl;
			cout<<"Leo Lelis"<<endl;
			cout<<"Dandi Maulana"<<endl;
			cout<<"Rizky Ridho"<<endl;
			cout<<"Salman Alfraid"<<endl;
			cout<<"Riswan Lauhim"<<endl;
			cout<<"Alta Ballah"<<endl;
			cout<<"Koko Ari"<<endl;
			cout<<"Arizky Wahyu"<<endl;
			cout<<"Arief Catur"<<endl;
			cout<<"Alwi Slamet"<<endl;
			cout<<"Marselino Ferdinan"<<endl;
			cout<<"Hugo Vidal"<<endl;
			cout<<"Brylian Adama"<<endl;
			cout<<"Michael Rumere"<<endl;
			cout<<"Andre Oktaviansyah"<<endl;
			cout<<"Dicky Kurniawan"<<endl;
			cout<<"Rizky Dwiyan"<<endl;
			cout<<"Fernando Pamungkas"<<endl;
			cout<<"Denny Agus"<<endl;
			cout<<"Muhammad Hidayat"<<endl;
			cout<<"Wahyudi"<<endl;
			cout<<"Sho Yamamoto"<<endl;
			cout<<"Julian Mancini"<<endl;
			cout<<"Ruy Aryanto"<<endl;
			cout<<"Januar Eka"<<endl;
			break;
			
		case 12 :
			cout<<"PSIS Semarang"<<endl;
			cout<<"--NAMA NAMA PEMAINYA--"<<endl;
		    cout<<"Carlos Fortes"<<endl;
			cout<<"Rio Saputro"<<endl;
			cout<<"Taisei Marukawa"<<endl;
			cout<<"Alfaendra Dewangga"<<endl;
			cout<<"Wahyu Tri Nugroho"<<endl;
			cout<<"Alie Sessay"<<endl;
			cout<<"Wahyu Prasetyo"<<endl;
			cout<<"Reza Irfana"<<endl;
			cout<<"Jonathan Cantillana"<<endl;
			cout<<"Oktafianus Fernando"<<endl;
			cout<<"Eduardus Aditya"<<endl;
			cout<<"Riyan Adriyansyah"<<endl;
			cout<<"Damas Damar"<<endl;
			cout<<"Hari Nur Yulianto"<<endl;
			cout<<"Wawan Febrianto"<<endl;
			cout<<"Bahril Fahreza"<<endl;
			cout<<"Jorry Guruh"<<endl;
			cout<<"Aqsha Sanishkara"<<endl;
			cout<<"Kartika Vadheyanto"<<endl;
			cout<<"Septian David Maulana"<<endl;
			cout<<"Farrel Arya"<<endl;
			cout<<"Guntur Tri Aji"<<endl;
			cout<<"Eka Febri Setiawan"<<endl;
			cout<<"Syihha Budin"<<endl;
			cout<<"Fredyan Wahyu"<<endl;
			cout<<"Ridho Syuhada"<<endl;
			cout<<"Yofandani Pranata"<<endl;
			cout<<"Taufik Hidayat"<<endl;
			cout<<"Delvin Rumbino"<<endl;
			cout<<"Fajar Setya"<<endl;
			break;
			
		case 13 :
			cout<<"Persib Bandung"<<endl;
			cout<<"--NAMA NAMA PEMAINYA--"<<endl;
			cout<<"I Made Wirawan"<<endl;
			cout<<"Teja Paku Alam"<<endl;
			cout<<"Fitrul Dwi Rustapa"<<endl;
			cout<<"Reky Rahayu"<<endl;
			cout<<"Henhen Herdiana"<<endl;
			cout<<"Viktor Igbonefo"<<endl;
			cout<<"Zalnando"<<endl;
			cout<<"Achmad Jufriyanto"<<endl;
			cout<<"Nick Kuipers"<<endl;
			cout<<"Kakang Rudianto"<<endl;
			cout<<"Bayu Fiqri"<<endl;
			cout<<"Eriyanto"<<endl;
			cout<<"David Rumakiek"<<endl;
			cout<<"Daisuke Sato"<<endl;
			cout<<"Dedi Kusnandar"<<endl;
			cout<<"Febri Hariyadi"<<endl;
			cout<<"Beckham Putra Nugraha"<<endl;
			cout<<"Abdul Aziz"<<endl;
			cout<<"Erwin Ramdani"<<endl;
			cout<<"Marc Klok"<<endl;
			cout<<"Rahmat Irianto"<<endl;
			cout<<"Ricky Kambuaya"<<endl;
			cout<<"Arsan Makarim"<<endl;
			cout<<"Robi Darwis"<<endl;
			cout<<"Frets Butuan"<<endl;
			cout<<"David Da Silva"<<endl;
			cout<<"Ciro Alves"<<endl;
			cout<<"Ezra Walian"<<endl;
			cout<<"Ridwan Ansori"<<endl;      
			cout<<""<<endl;
			break;
			
			
		case 14 :
			cout<<"Borneo FC"<<endl;
		    cout<<"--NAMA NAMA PEMAINYA--"<<endl;
		    cout<<"Muhammad Ilham"<<endl;
			cout<<"Fajar Fathur Rahman"<<endl;
			cout<<"Rifad Marasabessy"<<endl;
			cout<<"Paulo Sitanggang"<<endl;
			cout<<"Boaz Solossa"<<endl;
			cout<<"Muhammad Sihran"<<endl;
			cout<<"Gianluca Pandeynuwu"<<endl;
			cout<<"Serdy Ephyfano"<<endl;
			cout<<"Wahyudi Hamisi"<<endl;
			cout<<"Miftahul Ihsan"<<endl;
			cout<<"Muhammad Zulfikri"<<endl;
			cout<<"Nur Diansyah"<<endl;
			cout<<"Ilhamsyah"<<endl;
			cout<<"Safrudin Tahar"<<endl;
			cout<<"Terens Puhiri"<<endl;
			cout<<"Ahmad Surahman"<<endl;
			cout<<"Wiranto"<<endl;
			cout<<"Javlon Guseynov"<<endl;
			cout<<"Rabbani Tasnim"<<endl;
			cout<<"Pualam bahhari"<<endl;
			cout<<"sultan Samma"<<endl;
			cout<<"Wawan Febrianto"<<endl;
			cout<<"Jonathan Bustos"<<endl;
			cout<<"Matheus Pato"<<endl;
			cout<<"Stefano Lilypaly"<<endl;
			cout<<"Leo Guntara"<<endl;
			cout<<"Angga Saputro"<<endl;
			cout<<"Marckho Sandy"<<endl;
			cout<<"Kei Hirose"<<endl;
			cout<<"Torres"<<endl;
			break;
		
			cout<<"------MOHON MAAF BILA ADA SALAH PENYEBUTAN NAMA"<<endl;
			cout<<"-----------------------------------------"<<endl;
			cout<<"---BUATAN ARYA POKONAMAH-----";
	}
	return 0;
}
